name = "website"
pages_build_output_dir = ".build"
compatibility_date = "2025-01-01"

# Installing manually so I don't need pyproject.toml/package.json
[env.production.vars]
UNSTABLE_PRE_BUILD = "bun i csso-cli uglify-js && pip install lxml beautifulsoup4 nova-framework"
